defaults:
  - _self_
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

hydra:
  run:
    dir: .
  output_subdir: null


#config.yaml
experiment:
  seed: 42

environment:
  cuda: true

audio:
  sample_rate: 16000
  n_fft: 512
  hop_length: 160
  win_length: 400
  n_mels: 128
  use_mel: true
  log_mel: true
  max_frames: 256

splits:
    train: 0.8
    val: 0.1
    test: 0.1

dataloader:
  batch_size: 32
  shuffle: true
  num_workers: 2
  pin_memory: false
  prefetch_factor: 1
  persistent_workers: false

model:
  architecture: vgg16
  in_channels: 1
  out_channels: 64
  num_classes: 7
  kernel_size: 3
  stride: 1
  padding: 1
  dropout: 0.3
  max_pool_kernel: 2
  max_pool_stride: 2
  channels: [64, 128, 256, 512, 512]


optimizer:
  lr: 0.0003
  weight_decay: 0.01

training:
  epochs: 50
  log_every: 1
  use_amp: true
  amp_dtype: float16
  channels_last: true
  compile: false
  compile_mode: default
  cudnn_benchmark: true
  matmul_precision: medium
